### ISSUE TITLE
Suggestion: Change repository name

### ISSUE THREAD

**Issue by jonatanblockchain** [ontspace/util#1]
What about change the name per ontio-space or ontio-labs?

We already have:
ontio
ontio-cyano
ontio-community

**Comment by Honglei-Cong** [comment]
This org likes to collect 3rd party projects/packages for ontology platform.

Names which contains letter '-', will make package importing path containing '-'.
It's better if the name consisted only by alphabet letters.

**Comment by jonatanblockchain** [comment]
Ok!
